POST localhost:8000/v0/basic-combat HTTP/1.1
Host: localhost:8000
Content-Type: application/json
Content-Length: 206

{
    "attacker": {
        "hex_id": 3,
        "player_id": 125,
        "tokens": 19
        },
    "defender": {
        "hex_id": 9,
        "player_id": 88,
        "tokens": 22
        }
}
